Day-12
Numpy Library

In [2]:
import numpy as np

In [2]:
print(np.__version__)

1.25.0


Create a numPy ndarray object

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray we can pass a list, touple or any array like object into the array() method.

Use a tuple to create a numpy array

In [2]:
import numpy as np
arr = np.array((1,2,3,4))
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


Dimensions in arrays

Create a 0d array

In [4]:
arr = np.array(23)
print(arr)
print(arr.ndim)

23
0


1D array is the array that has 0D array as its elements.

In [5]:
arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


Creating 2D array

In [7]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


3D array has 2D array (Matrices) as its elements

In [9]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


Higher dimension array

When the array is created, you can define the number of dimensions by using the ndmin argument

Create an array with 5 dimension and verify that it has 5 dimension

In [11]:
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
5


In [14]:
arr= np.array([[[[[1,2,3,4,5]]]]])
print(arr.ndim)

5


Numpy array indexing

You can access an array by referring to its index number

In [15]:
arr = np.array([1,3,4,5])
print(arr[2])

4


In [16]:
arr = np.array([12,65,7,89,34,54,67,90,23,56,76,43])
print(arr[2]+arr[6]+arr[3])

163


Access 2d arrays

In [21]:
arr= np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,2])
print(arr[0,3])
print(arr[1,3])

7
4
8


Add the first element of row 1 ndd lasst element

In [23]:
arr= np.array([[1,2,3,4],[5,6,7,8]])
print(arr[0,0]+arr[1,3])


9


Access 3-D arrays

In [8]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,0,2])
print(arr[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
12


Negative indexing

In [11]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[-2,-1])

5


Numpy array Slicing

Slicing in python means taking elements from one givenn index to another given index.  
We can slice instead of index like this: [start:end].
We caan also define the step like this:[start:end:step].

In [12]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:6])

[2 3 4 5 6]


Slice elements fom index 4 to the end of the array

In [13]:
arr = np.array([1,2,3,4,5,6])
print(arr[4:])

[5 6]


If we want to gap between the numbers

In [15]:
arr = np.array([1,2,3,4,5,6])
print(arr[::2])

[1 3 5]


Slicing 2-D array

In [22]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0,1:])
print(a[1,::2])

[2 3 4 5]
[ 6  8 10]


Imp: From both elements return index 2

In [23]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0:2,2])

[3 8]


Slice index 1 to 4(not included), this will return a 2-D array

In [24]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0:2,1:4])

[[2 3 4]
 [7 8 9]]
