Day-13

NumPy Part-2

Data types in python.  
Numpy has some extra data types.  
 
i-integer
b-boolean
u-unsigned integer
f-float
c-complex float
m-timedelta
M-datetime
o-object
s-string
U-unicode string
V-Fixed chunk of memeory for other type (void)

Checking the data types of an array

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [3]:
arr = np.array(["hi","Hello"])
print(arr.dtype)

<U5


Creating arrays with a defined Data type

In [1]:
import numpy as np

In [4]:

arr = np.array([9,2,3,4], dtype= 'S')
print(arr)
print(arr.dtype)

[b'9' b'2' b'3' b'4']
|S1


CReate an array with data type 4 bytes integer

In [5]:
arr = np.array([1,2,3,4], dtype= 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


NumPy array shape

The shape of an array is the elements in each dimension

In [6]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)


(2, 4)


In [8]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print(arr.shape)


[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


Joining numPy arrays

In [11]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,6])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 6]


Join two 2-D arrays along rows(axis=1) Rows

In [12]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[2,4,6],[3,6,9]])

arr= np.concatenate((arr1,arr2),axis=1)
print(arr)


[[1 2 3 2 4 6]
 [4 5 6 3 6 9]]


Join two 2-D array along coloumn(axis=0)

In [13]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[2,4,6],[3,6,9]])

arr= np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2 3]
 [4 5 6]
 [2 4 6]
 [3 6 9]]


Spliting NumPy arrays

Splitting is reverse of joining. Joining mearges multiple arrays into one and spitting one array into multiple

Split the array into 3 Parts

In [17]:
arr = np.array([1,2,3,4,5,6,7])
new = np.array_split(arr,3)
new1 = np.array_split(arr,4)
new2 = np.array_split(arr,7)

print(new)
print(new1)
print(new2)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7])]


Ravel & flatten- Converts multidimensional into 1d array

In [22]:
m = np.array([[[1,2,3],[4,5,6]],[[5,8,9],[1,6,3]]])
print(m)
print(m.shape)
n = m.ravel()
print(n)

[[[1 2 3]
  [4 5 6]]

 [[5 8 9]
  [1 6 3]]]
(2, 2, 3)
[1 2 3 4 5 6 5 8 9 1 6 3]


In [23]:
m = np.array([[[1,2,3],[4,5,6]],[[5,8,9],[1,6,3]]])
print(m)
print(m.shape)
n = m.flatten()
print(n)

[[[1 2 3]
  [4 5 6]]

 [[5 8 9]
  [1 6 3]]]
(2, 2, 3)
[1 2 3 4 5 6 5 8 9 1 6 3]


Arithmetic operations in numpy arrays

Addition

In [25]:
x = np.array([1,2,3,4,5])
y = x+3
print(x)
print(y)

[1 2 3 4 5]
[4 5 6 7 8]


In [28]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
z = x+y
print(x)
print(y)
print(z)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]


In [29]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
z = np.add(x,y)
print(z)

[ 7  9 11 13 15]


Subtraction

In [30]:
x = np.array([1,2,3,4,5])
y = x-4
print(x)
print(y)

[1 2 3 4 5]
[-3 -2 -1  0  1]


In [32]:
y = np.array([6,7,8,9,10])
x = np.array([1,2,3,4,5])
z = y-x
print(x)
print(y)
print(z)

[1 2 3 4 5]
[ 6  7  8  9 10]
[5 5 5 5 5]


In [33]:
y = np.array([6,7,8,9,10])
x = np.array([1,2,3,4,5])
z = np.subtract(y,x)
print(x)
print(y)
print(z)

[1 2 3 4 5]
[ 6  7  8  9 10]
[5 5 5 5 5]


Multiplication

In [2]:
import numpy as np
x = np.array([1,2,3,4])
y =x*3
print(y)

[ 3  6  9 12]


In [4]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
z = x*y
print(x)
print(y)
print(z)

[1 2 3 4]
[5 6 7 8]
[ 5 12 21 32]


In [5]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
z = np.multiply(x,y)
print(x)
print(y)
print(z)

[1 2 3 4]
[5 6 7 8]
[ 5 12 21 32]


Division

In [6]:
x = np.array([1,2,3,4,5])
y = x/3
print(y)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [7]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
z = np.divide(x,y)
print(z)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


Modulous

In [8]:
x = np.array([10,15,20,25])
y = x%3
print(y)

[1 0 2 1]


In [10]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
z = x%y
m= y%x
print(z)
print(m)

[1 2 3 4 5]
[0 1 2 1 0]


In [12]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
z = np.mod(x,y)
print(x)
print(y)
print(z)

[1 2 3 4 5]
[ 6  7  8  9 10]
[1 2 3 4 5]


Arithmetic operations in 2-D array

In [14]:
n1 = np.array([[1,2,3],[4,5,6]])
n2 = np.array([[2,4,6],[3,6,9]])
arr = n1+n2
print(n1)
print(n2)
print(arr)

[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [3 6 9]]
[[ 3  6  9]
 [ 7 11 15]]


In [15]:
n1 = np.array([[1,2,3],[4,5,6]])
n2 = np.array([[2,4,6],[3,6,9]])
x = n2-n1
print(n1)
print(n2)
print(x)

[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [3 6 9]]
[[ 1  2  3]
 [-1  1  3]]


In [16]:
n1 = np.array([[1,2,3],[4,5,6]])
n2 = np.array([[2,4,6],[3,6,9]])
y = n1*n2
print(n1)
print(n2)
print(y)

[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [3 6 9]]
[[ 2  8 18]
 [12 30 54]]


In [17]:
n1 = np.array([[1,2,3],[4,5,6]])
n2 = np.array([[2,4,6],[3,6,9]])
z = n1/n2
print(n1)
print(n2)
print(z)

[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [3 6 9]]
[[0.5        0.5        0.5       ]
 [1.33333333 0.83333333 0.66666667]]


In [18]:
n1 = np.array([[1,2,3],[4,5,6]])
n2 = np.array([[2,4,6],[3,6,9]])
n3 = n1%n2
print(n1)
print(n2)
print(n3)

[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [3 6 9]]
[[1 2 3]
 [1 5 6]]


Arithmetic operation- 3D array

In [20]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[[2,4,6,8],[3,6,9,12]]])
x = n1+n2
print(n1)
print(n2)
print(x)
print(x.ndim)

[[[1 2 3 4]
  [5 6 7 8]]]
[[[ 2  4  6  8]
  [ 3  6  9 12]]]
[[[ 3  6  9 12]
  [ 8 12 16 20]]]
3


In [21]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[[2,4,6,8],[3,6,9,12]]])
x = n1-n2
print(x)
print(x.ndim)

[[[-1 -2 -3 -4]
  [ 2  0 -2 -4]]]
3


In [23]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[[2,4,6,8],[3,6,9,12]]])
x = n1*n2
print(x)
print(x.ndim)

[[[ 2  8 18 32]
  [15 36 63 96]]]
3


In [24]:
n1 = np.array([[[1,2,3,4],[5,6,7,8]]])
n2 = np.array([[[2,4,6,8],[3,6,9,12]]])
x = n1/n2
print(x)
print(x.ndim)

[[[0.5        0.5        0.5        0.5       ]
  [1.66666667 1.         0.77777778 0.66666667]]]
3


Unique Function

In [28]:
k = np.array([12,23,5,64,78,56,8,9,10,11,45,78,9,23,56,48,16])
print(k)
x = np.unique(k)
print(x)

[12 23  5 64 78 56  8  9 10 11 45 78  9 23 56 48 16]
[ 5  8  9 10 11 12 16 23 45 48 56 64 78]


In [29]:
k = np.array([12,23,5,64,78,56,8,9,10,11,45,78,9,23,56,48,16])
print(k)
x = np.unique(k,return_index= True)
print(x)

[12 23  5 64 78 56  8  9 10 11 45 78  9 23 56 48 16]
(array([ 5,  8,  9, 10, 11, 12, 16, 23, 45, 48, 56, 64, 78]), array([ 2,  6,  7,  8,  9,  0, 16,  1, 10, 15,  5,  3,  4], dtype=int64))


In [30]:
k = np.array([12,23,5,64,78,56,8,9,10,11,45,78,9,23,56,48,16])
print(k)
x = np.unique(k,return_index= True, return_counts=True)
print(x)

[12 23  5 64 78 56  8  9 10 11 45 78  9 23 56 48 16]
(array([ 5,  8,  9, 10, 11, 12, 16, 23, 45, 48, 56, 64, 78]), array([ 2,  6,  7,  8,  9,  0, 16,  1, 10, 15,  5,  3,  4], dtype=int64), array([1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2], dtype=int64))


Delete

In [31]:
a = np.array([12,13,14,15])
print(a)
print()
d = np.delete(a,[2])
print(d)

[12 13 14 15]

[12 13 15]


In [36]:
x = np.array([[2,3,4,5],[6,7,8,9],[2,4,6,8]])
print(x)
print()
m = np.delete(x ,1, axis = 0)
n = np.delete(x ,1, axis = 1)

print(m)
print()
print(n)

[[2 3 4 5]
 [6 7 8 9]
 [2 4 6 8]]

[[2 3 4 5]
 [2 4 6 8]]

[[2 4 5]
 [6 8 9]
 [2 6 8]]
